FuturaMod1/Models/Places.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuturaMod1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string CareType { get; set; }
        public string Provider { get; set; }
        public string OrgType { get; set; }
        public string Remote { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string PlaceType { get; set; }
        public string Descri { get; set; }
    }
}

FuturaMod1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FuturaMod1.Controllers
{
    public class HomeController : Controller
    {
        //public ActionResult Index()
        //{
        //    return View();
        //}

        //public ActionResult About()
        //{
        //    ViewBag.Message = "Your application description page.";

        //    return View();
        //}

        //public ActionResult Contact()
        //{
        //    ViewBag.Message = "Your contact page.";

        //    return View();
        //}
    }
}

FuturaMod1/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FuturaMod1.Models;

// You cannot carry anymore.

namespace FuturaMod1.Controllers
{
    public class PlacesController : Controller
    {
        private PlacesEntities db = new PlacesEntities();
        // static string to store postcode
        private static string thePost = "";
        private static bool isChanged = false;
        private static bool mapSelected = true;
        private static string yourChoice = "nothing";
        private static List<SelectListItem> postcodeList;

        // GET: Start Page
        public ActionResult Start()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Start(string postCode)
        {
            // bind the input of postcode from cshtml
            thePost = postCode;
            return RedirectToAction("Index");
        }

        // GET: Start Page
        public ActionResult StartError()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StartError(string postCode)
        {
            // bind the input of postcode from cshtml
            thePost = postCode;
            return RedirectToAction("Index");
        }

        public ActionResult About()
        {
            return View();
        }

        // GET: Places
        public ActionResult Index(string postString, string searchString)
        {
            // use viewbag to display postcode and search name in view
            //thePost = postString;
            ViewBag.ShowPost = thePost;
            isChanged = false;
            if (postString != thePost)
            {
                ViewBag.ShowName = "";
                isChanged = true;
                searchString = null;
            }
            else
            {
                ViewBag.ShowName = searchString;
            }

            // check if user changed the postcode
            string getPost = postString;
            var places = from p in db.Places
                         where p.Postcode == thePost
                         select p;
            if (getPost != null) // if the page is postback
            {
                ViewBag.ShowPost = getPost;
                thePost = getPost;
                places = from p in db.Places
                         where p.Postcode == getPost
                         select p;
            }

            // not finding anything, return to start page, display error
            if (!places.Any())
            {
                return RedirectToAction("StartError");
            }

            // handles manual search function
            if (!String.IsNullOrEmpty(searchString))
            {
                places = places.Where(p => p.Name.Contains(searchString) || p.Address.Contains(searchString) || p.PlaceType.Contains(searchString));
            }

            // display error when nothing is there
            ViewBag.Err = "";
            if (!places.Any() && !isChanged)
            {
                ViewBag.Err = "No results found, so we display everything for you instead.";
                places = from p in db.Places
                         where p.Postcode == thePost
                         select p;
            }

            // find the places with matched postcode
            return View(places.ToList());
        }

        // GET: Places/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Places places = db.Places.Find(id);
            if (places == null)
            {
                return HttpNotFound();
            }
            return View(places);
        }

        public ActionResult Home()
        {
            return View();
        }
        
        public ActionResult Explore()
        {
            // Get all the distinct suburb - postcode pairs to use for selecting postcodes on drop down lists
            postcodeList = new List<SelectListItem>();
            var places = (from p in db.Places
                          select new { p.Suburb, p.Postcode }).Distinct();

            // Create the Text to display for the dropdown list and its value
            foreach (var item in places)
            {
                postcodeList.Add(new SelectListItem() { Text = item.Suburb.ToUpper() + " - " + item.Postcode, Value = item.Postcode });
            }

            ViewBag.postcodeList = postcodeList;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Explore(string inBtn, string postcode)
        {
            if (!string.IsNullOrEmpty(postcode) && string.IsNullOrEmpty(inBtn))
            {
                thePost = postcode;
                return RedirectToAction("Index");
            }
            else
            {
                switch (inBtn)
                {
                    case "relax":
                        yourChoice = "Relaxation";
                        return RedirectToAction("IndexNew");
                    case "art":
                        yourChoice = "Art Space";
                        return RedirectToAction("IndexNew");
                    case "cook":
                        yourChoice = "Cooking";
                        return RedirectToAction("IndexNew");
                    case "club":
                        yourChoice = "Club";
                        return RedirectToAction("IndexNew");
                    case "swim":
                        yourChoice = "Swimming Pool";
                        return RedirectToAction("IndexNew");
                    case "park":
                        yourChoice = "Park";
                        return RedirectToAction("IndexNew");
                    case "garden":
                        yourChoice = "Garden";
                        return RedirectToAction("IndexNew");
                    case "market":
                        yourChoice = "Market";
                        return RedirectToAction("IndexNew");
                    case "library":
                        yourChoice = "Library";
                        return RedirectToAction("IndexNew");
                    case "restaurantCafe":
                        yourChoice = "Restaurants and Cafes";
                        return RedirectToAction("IndexNew");
                    case "bakery":
                        yourChoice = "Bakery";
                        return RedirectToAction("IndexNew");
                    case "takeaway":
                        yourChoice = "Takeaway";
                        return RedirectToAction("IndexNew");
                    case "worship":
                        yourChoice = "Place of Worship";
                        return RedirectToAction("IndexNew");
                    case "dance":
                        yourChoice = "Dance";
                        return RedirectToAction("IndexNew");
                    default:
                        return View();
                }
            }
        }

        //public ActionResult HomeIn()
        //{
        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult HomeIn(string inBtn)
        //{
        //    switch (inBtn)
        //    {
        //        case "relax":
        //            yourChoice = "Relaxation";
        //            return RedirectToAction("IndexNew");
        //        case "art":
        //            yourChoice = "Art Space";
        //            return RedirectToAction("IndexNew");
        //        case "cook":
        //            yourChoice = "Cooking";
        //            return RedirectToAction("IndexNew");
        //        case "club":
        //            yourChoice = "Club";
        //            return RedirectToAction("IndexNew");
        //        case "swim":
        //            yourChoice = "Swimming Pool";
        //            return RedirectToAction("IndexNew");
        //        default:
        //            return View();
        //    }
        //}

        //public ActionResult HomeOut()
        //{
        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult HomeOut(string outBtn)
        //{
        //    switch (outBtn)
        //    {
        //        case "park":
        //            yourChoice = "Park";
        //            return RedirectToAction("IndexNew");
        //        case "garden":
        //            yourChoice = "Garden";
        //            return RedirectToAction("IndexNew");
        //        default:
        //            return View();
        //    }
        //}

        public ActionResult IndexNew()
        {
            var places = from p in db.Places
                         where p.PlaceType == yourChoice
                         select p;
            return View(places.ToList());
        }

        public ActionResult Activities()
        {
            return View();
        }


        //// GET: Places/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Places/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Name,Address,Suburb,State,Postcode,CareType,Provider,OrgType,Remote,Latitude,Longitude,PlaceType,Desc")] Places places)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Places.Add(places);

FuturaMod1/Views/Places/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Website Info Section -->
<div id="about">
    <header>
        <div class="title-header-img">
            <div class="section-title text-center">
                <h1>About Social Isolation</h1>
                <hr />
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            <div class="text-center col-xs-12 col-md-12">
                <h2>What are senior loneliness and social isolation?</h2>
            </div>
            <div class="col-xs-12 col-md-4 text-center">
                <img src="~/Content/img/loneliness.png" class="img-responsive center-block" alt="">
            </div>
            <div class="col-xs-12 col-md-8">
                <div class="outer-container">
                    <div class="middle-container">
                        <div class="inner-container">
                            <p>
                                <strong>Loneliness:</strong> The feeling of lack or loss of companionship.
                            </p>
                            <p>
                                <strong>Social isolation:</strong>  Having little relationship with others.
                            </p>
                            <p>
                                Social isolation may lead to feelings of loneliness and loneliness is associated with the quality of social bonds.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="info-seperator col-xs-12 col-md-12">
                <hr />
            </div>

            <div class="text-center col-xs-12 col-md-12">
                <h2 class="text-center">Elderly Australians are more likely to live on their own and go out less often.</h2>
            </div>
            <div class="col-xs-12 col-md-8">
                <div class="outer-container">
                    <div class="middle-container">
                        <div class="inner-container">
                            <p>
                                <ul>
                                    <li>Elderly Australians are more likely to live alone and go out less often.</li>
                                    <li>29.7% of people aged 75-84 live alone.</li>
                                    <li>35.2% of people aged over 85 live alone.</li>
                                    <li>Elderly women (32%) are much more likely to live alone than elderly men (17%).</li>
                                    <li>59% of elderly people who live alone have reported that they are widowed.</li>
                                    <li>16.2% of people aged 65 and over do not leave home as frequently as before.</li>
                                    <li>46.8% of elderly Australians with a severe disability do not leave home as often as they wished.</li>
                                </ul>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-4 text-center">
                <img src="~/Content/img/solitudeStats.png" class="img-responsive center-block" alt="">
            </div>
            <div class="info-seperator col-xs-12 col-md-12">
                <hr />
            </div>

            <div class="text-center col-xs-12 col-md-12">
                <h2>How serious are social isolation and loneliness?</h2>
            </div>
            <div class="col-xs-12 col-md-4 text-center">
                <img src="~/Content/img/seriousness.png" class="img-responsive center-block" alt="">
            </div>
            <div class="col-xs-12 col-md-8">
                <div class="outer-container">
                    <div class="middle-container">
                        <div class="inner-container">
                            <p>
                                <ul>
                                    <li>Social isolation and loneliness will lead to poorer mental health and physical health</li>
                                    <li>Elderly people may have feelings of anger, sadness, depression, worthlessness, resentment, emptiness, vulnerability and pessimism</li>
                                    <li>
                                        If someone you know has a serious case of deression, there are many organisations that can help:
                                        <ul>
                                            <li><a href="https://www.beyondblue.org.au/">https://www.beyondblue.org.au/</a></li>
                                            <li><a href="https://au.reachout.com/">https://au.reachout.com/</a></li>
                                            <li><a href="https://www.blackdoginstitute.org.au/">https://www.blackdoginstitute.org.au/</a></li>
                                            <li><a href="https://www.sane.org/">https://www.sane.org/</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="info-seperator col-xs-12 col-md-12">
                <hr />
            </div>

            <div class="text-center col-xs-12 col-md-12">
                <h2>Strategies for social isolation and loneliness</h2>
            </div>
            <div class="col-xs-12 col-md-8">
                <div class="outer-container">
                    <div class="middle-container">
                        <div class="inner-container">
                            <p>
                                <ul>
                                    <li>Introducing interventions as part of a wider strategic approach</li>
                                    <li>Targeting specific groups of elderly people</li>
                                    <li>Using existing community resources</li>
                                    <li>Using volunteers to run programs</li>
                                    <li>Using targeted and tailored approaches</li>
                                    <li>Involving older people in the planning, delivery and evaluation of programs</li>

                                </ul>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-4 text-center">
                <img src="~/Content/img/strategy.png" class="img-responsive center-block" alt="">
            </div>
        </div>
        <div class="info-seperator col-xs-12 col-md-12">
            <hr />
        </div>

        <div class="text-center col-xs-12 col-md-12">
            <h2>Projected Prevalence of Elderly Social Isolation in Victoria 2008-2040</h2>
        </div>

        <div class='tableauPlaceholder' id='viz1538707234035' style='position: relative'>
            <noscript>
                <a href='#'>
                    <img alt='Projected Prevalence of Elderly Social Isolation in Victoria 2008-2040 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;Projectedprevalence&#47;Sheet1&#47;1_rss.png' style='border: none' />
                </a>
            </noscript>
            <object class='tableauViz' style='display:none;'>
                <param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' />
                <param name='embed_code_version' value='3' />
                <param name='site_root' value='' />
                <param name='name' value='Projectedprevalence&#47;Sheet1' />
                <param name='tabs' value='no' />
                <param name='toolbar' value='yes' />
                <param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Pr&#47;Projectedprevalence&#47;Sheet1&#47;1.png' />
                <param name='animate_transition' value='yes' />
                <param name='display_static_image' value='yes' />
                <param name='display_spinner' value='yes' />
                <param name='display_overlay' value='yes' />
                <param name='display_count' value='yes' />
            </object>
        </div>
        <script type='text/javascript'>
            var divElement = document.getElementById('viz1538707234035');
            var vizElement = divElement.getElementsByTagName('object')[0];
            vizElement.style.width = '100%';
            //vizElement.style.height = (divElement.offsetWidth * 0.75) + 'px';
            vizElement.style.height = '80vh';

            var scriptElement = document.createElement('script');
            scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';
            vizElement.parentNode.insertBefore(scriptElement, vizElement);
        </script>
        <div class="info-seperator col-xs-12 col-md-12">
            <hr />
        </div>

        <div class="text-center">
            <p>Now that you know more about social isolation. Lets do something to reduce it!</p>
            <a href='@Url.Action("Explore", "Places")' class="btn btn-lg btn-success" style="color:#fff;">Explore Places</a>
        </div>
        <div class="info-seperator col-xs-12 col-md-12">
            <hr />
        </div>

        <h4>References</h4>
        <p>
            <ol>
                <li>Pate, A (2014). ‘Social Isolation: Its impact on the mental health of older Victorians’, COTA Victoria, Working Paper No. 1, 12.</li>
                <li>Productivity Commission (2015). ‘Report on Government Services’, Chapter 13, Australian Government, Canberra, 67.</li>
                <li>Benevolent Society (2013). ‘Promoting social networks for older people in community aged care’, Research to Practice Briefing 2.</li>
                <li>NARI and COTA Victoria, ‘Healthy Ageing Literature Review’, 2012, 38.</li>
                <li>https://www.acsa.asn.au/getattachment/Publications-Submissions/Social-Isolation-and-Loneliness/1015-Social-Isolation-and-Loneliness-Paper.pdf.aspx?lang=en-AU</li>
            </ol>
        </p>
    </div>
</div>


@*   <script type="text/javascript">
        function initViz() {
            var containerDiv = document.getElementById("viz1538450430335"),
                url = "https://public.tableau.com/views/supportforelders/Sheet1?:embed=y&:display_count=yes",
                options = {
                    hideTabs: true,
                    onFirstInteractive: function () {
                        console.log("Run this code when the viz has finished loading.");
                    }
                };

            var viz = new tableau.Viz(containerDiv, url, options);
            // Create a viz object and embed it in the container div.
        }
    </script>*@

@*<script src="https://public.tableau.com/javascripts/api/tableau-2.min.js"></script>
    <script>
        var placeholderDiv = document.getElementById("tableauViz");
        var url = "https://public.tableau.com/views/supportforelders/Sheet1?:embed=y&:display_count=yes";
        var options = {
            hideTabs: true,
            width: "800px",
            height: "700px",
            onFirstInteractive: function () {
                // The viz is now ready and can be safely used.
            }
        };
        var viz = new tableau.Viz(placeholderDiv, url, options);
    </script>*@

FuturaMod1/Views/Places/Activities.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Places and Activities Info Section -->
<div class="places-activities-info start-info">
    <div class="container">
        <div class="section-title text-center">
            <h1>Places and Activities</h1>
            <hr />
        </div>
        <p>
            VIC senior Life aims to help tackle loneliness in elder Victorians by suggesting suitable places and activities for elders where they can connect with others, explore new place to keep them occupied and enjoy life.
        </p>
        <br />
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <img src="~/Content/img/parkph.png" class="img-responsive" width="150" height="150"> @*center-block">*@
                @*<div class="text-center">*@
                <h3>Parks</h3>
                @*</div>*@
                <p>Parks to help senior citizens better enjoy life, by taking a walk along the park and socialising with other peers.</p>
            </div>
            <div class="col-xs-12 col-sm-3">
                <img src="~/Content/img/relaxationph.png" class="img-responsive" width="150" height="150"> @*center-block">*@
                @*<div class="text-center">*@
                <h3>Relaxation</h3>
                @*</div>*@
                <p>Fun and effective elderly relaxation activities are an important part of overall senior care. And can help give relief and distraction from burdens that befall the aging.</p>
            </div>
            <div class="col-xs-12 col-sm-3">
                <img src="~/Content/img/gardenph.png" class="img-responsive" width="150" height="150"> @*center-block">*@
                @*<div class="text-center">*@
                <h3>Gardens</h3>
                @*</div>*@
                <p>With no shortage of blissful spring days on the horizon, there's no better time to be a little adventurous and explore some gardens.</p>
            </div>
            <div class="col-xs-12 col-sm-3">
                <img src="~/Content/img/cookingph.png" class="img-responsive" width="150" height="150"> @*center-block">*@
                @*<div class="text-center">*@
                <h3>Cooking</h3>
                @*</div>*@
                <p>
                    Cooking class is a wonderful opportunity for older people in the community to renew
                    their interest in cooking and eating healthily, and to make friends whilst learning in a
                    fun and supportive environment.
                </p>
            </div>
            <div class="col-xs-12 col-sm-3">
                <img src="~/Content/img/poolph.png" class="img-responsive" width="150" height="150"> @*center-block">*@
                @*<div class="text-center">*@
                <h3>Swimming Pool</h3>
                @*</div>*@
                <p>
                    Swimming pools are a great resource for seniors in terms of health and socialization.
                    A splash in the pool may help older adults achieve their fitness goals.
                </p>
            </div>
            <div class="col-xs-12 col-sm-3">
                <img src="~/Content/img/artph.png" class="img-responsive" width="150" height="150"> @*center-block">*@
                @*<div class="text-center">*@
                <h3>Art Space</h3>
                @*</div>*@
                <p>
                    Art programs provide tangible physical and mental health benefits by providing
                    opportunities for participation, and for maintaining hand strength and coordination.
                </p>
            </div>
            <div class="col-xs-12 col-sm-4">
                <img src="~/Content/img/clubph.png" class="img-responsive" width="150" height="150"> @*center-block">*@
                @*<div class="text-center">*@
                <h3>Seniors Club</h3>
                @*</div>*@
                <p>
                    The club provide a relaxed environment where people can enjoy the company of
                    others and participate in a range of social activities.
                </p>
            </div>
        </div>
    </div>
</div>

FuturaMod1/Views/Places/Delete.cshtml
@model FuturaMod1.Models.Places

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Places</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Suburb)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Suburb)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Postcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Postcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CareType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CareType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Provider)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Provider)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrgType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrgType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remote)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>